### PR TITLE
Fix/364 unique pipeline consortium

### LINKED ISSUE #364: Unique Pipeline and Consortia Names
# Problem
Pipeline and Consortia names should be unique.
# Solution
- Check before saving either via their respective `save` GraphQL calls or some sort of `onBlur` action called when the user leaves the name field.
- Display a Bootstrap alert to users when a duplicate name is used.

### PR DESCRIPTION
**Pull request by kalitopix**
# Problem
referenced issue(s):

# Solution

# Testing

closes #364

### CODE REVIEW

File: packages/coinstac-ui/app/render/components/pipelines/pipeline.jsx [hunk 1]
```diff
@@ -437,12 +437,11 @@ class Pipeline extends Component {
       });
 
       notifySuccess({ message: 'Pipeline Saved.' });
-    }).catch((error) => {
-      notifyError({ message: error.message });
+    }).catch(({ graphQLErrors }) => {
+      console.log(graphQLErrors);
```
Comment (rssk) [inline packages/coinstac-ui/app/render/components/pipelines/pipeline.jsx]: this log intended?

**Review by rssk — CHANGES_REQUESTED** [review]

File: packages/coinstac-ui/app/render/components/pipelines/pipeline.jsx (hunk 1 above)
Comment (kalitopix) [reply packages/coinstac-ui/app/render/components/pipelines/pipeline.jsx]: yes. want to remove?

**Review by rssk — APPROVED** [review]
