### PR TITLE
Fix/918 pipeline edit fail

### LINKED ISSUE #918: Pipeline edit fails and styling broken

### PR DESCRIPTION
**Pull request by kalitopix**
# Problem
referenced issue(s):

# Solution

# Testing

closes #918

### CODE REVIEW

File: packages/coinstac-ui/app/render/components/consortia/consortia-list.jsx [hunk 1]
```diff
@@ -6,9 +6,11 @@ import { compose, graphql, withApollo } from 'react-apollo';
 import { ipcRenderer } from 'electron';
 import classNames from 'classnames';
 import { orderBy } from 'lodash';
-import {
-  Button, Menu, MenuItem, TextField, Typography,
-} from '@material-ui/core';
+import Button from '@material-ui/core/Button';
+import Menu from '@material-ui/core/Menu';
+import MenuItem from '@material-ui/core/MenuItem';
```
Comment (rssk) [inline packages/coinstac-ui/app/render/components/consortia/consortia-list.jsx:11]: whats up with all these import changes?

**Review by rssk — CHANGES_REQUESTED** [review]
Questions, and merge conflicts to fix, thanks!

File: packages/coinstac-ui/app/render/components/consortia/consortia-list.jsx (hunk 1 above)
Comment (kalitopix) [reply packages/coinstac-ui/app/render/components/consortia/consortia-list.jsx:11]: When I tried to import elements using named imports, styles were broken.
