### PR TITLE
Fixing issues with duplicated consortia owners/members

### LINKED ISSUE #517: UI: Consortia Members and Owners Saved 2x in Database
# Problem

Same as title

# Tasks

Fix it.

### PR DESCRIPTION
**Pull request by pixelsaurus**
# Problem
Now sure how/why many packages files ended up changed. Didn't add or commit them. 

closes #517

### CODE REVIEW

File: packages/coinstac-ui/app/render/components/consortia/consortium-tabs.jsx [hunk 1]
```diff
@@ -106,19 +107,23 @@ class ConsortiumTabs extends Component {
...
+      //this.props.removeUserRole(user.id, 'consortia', this.state.consortium.id, 'member');
+      //this.props.removeUserRole(user.id, 'consortia', this.state.consortium.id, 'owner');
     };
   }
 
   saveConsortium(e) {
     e.preventDefault();
 
+    /* This is creating a duplicate consortia owner. Why is this here?
+    //
```
Comment (rssk) [inline packages/coinstac-ui/app/render/components/consortia/consortium-tabs.jsx:120]: not sure either.... :-(

File: packages/coinstac-ui/app/render/components/consortia/consortium-tabs.jsx [hunk 2]
```diff
@@ -106,19 +107,23 @@ class ConsortiumTabs extends Component {
   removeMemberFromConsortium(user) {
     return () => {
       this.props.leaveConsortium(this.state.consortium.id, user.id);
-      this.props.removeUserRole(user.id, 'consortia', this.state.consortium.id, 'member');
-      this.props.removeUserRole(user.id, 'consortia', this.state.consortium.id, 'owner');
+      //this.props.removeUserRole(user.id, 'consortia', this.state.consortium.id, 'member');
```
Comment (rssk) [inline packages/coinstac-ui/app/render/components/consortia/consortium-tabs.jsx]: what issues were these causing? In general, which you did do below, its nice to have comments for commented out sections

File: package.json [hunk 3]
```diff
@@ -3,7 +3,10 @@
   "version": "2.0.0",
   "description": "Decentralized Analyses Made Easy",
   "main": "index.js",
-  "dependencies": {},
+  "dependencies": {
+    "bluebird": "^3.5.1",
```
Comment (rssk) [inline package.json]: hmmm, not sure why these are here

File: packages/coinstac-ui/app/render/components/consortia/consortium-about.jsx [hunk 4]
```diff
@@ -45,19 +45,20 @@ export default class ConsortiumAbout extends Component {
...
   }
 
   toggleOwner(consUser) {
     const { addUserRole, consortium, owner, removeUserRole, user } = this.props;
     return () => {
-      if (owner && consUser.id !== user.id) {
-        if (consUser.owner) {
-          removeUserRole(consUser.id, 'consortia', consortium.id, 'owner');
-        } else {
+      // if (owner && consUser.id !== user.id) {
```
Comment (rssk) [inline packages/coinstac-ui/app/render/components/consortia/consortium-about.jsx]: same here about comments

File: packages/coinstac-ui/app/render/components/consortia/consortium-about.jsx [hunk 5]
```diff
@@ -162,14 +163,15 @@ export default class ConsortiumAbout extends Component {
                           <Checkbox
                             onChange={this.toggleOwner(consUser)}
                             checked={consUser.owner ? true : false}
-                            disabled={!owner || consUser.id === user.id}
+                            //disabled={!owner || consUser.id === user.id}
```
Comment (rssk) [inline packages/coinstac-ui/app/render/components/consortia/consortium-about.jsx]: and here

**Review by rssk — CHANGES_REQUESTED** [review]

File: packages/coinstac-ui/app/render/components/consortia/consortia-list.jsx [hunk 6]
```diff
@@ -286,17 +286,19 @@ class ConsortiaList extends Component {
     }
 
     this.props.saveAssociatedConsortia({ id: consortiumId, activePipelineId });
-    this.props.addUserRole(user.id, 'consortia', consortiumId, 'member');
-    this.props.joinConsortium(consortiumId);
+    //this.props.addUserRole(user.id, 'consortia', consortiumId, 'member');
```
Comment (rssk) [inline packages/coinstac-ui/app/render/components/consortia/consortia-list.jsx]: ?

File: packages/coinstac-ui/app/render/components/consortia/consortium-about.jsx [hunk 7]
```diff
@@ -46,19 +46,20 @@ export default class ConsortiumAbout extends Component {
 
   addMember() {
     const newMember = this.state.newMember;
+    console.log(newMember[0].id);
```
Comment (rssk) [inline packages/coinstac-ui/app/render/components/consortia/consortium-about.jsx]: ?

File: packages/coinstac-api-server/src/data/resolvers.js [hunk 8]
```diff
@@ -437,14 +437,15 @@ const resolvers = {
           rethink.table('consortia').get(args.consortiumId)('members')
           .contains(userId).run(connection)
         ).then((result) => {
+          console.log(result);
```
Comment (rssk) [inline packages/coinstac-api-server/src/data/resolvers.js]: ?

**Review by rssk — APPROVED** [review]
